# Recurring billing browser wiring and storage policy checklist.
assert_file scripts/test_billing_ui.js "billing UI deterministic test exists"
assert_contains api/_billing-domain.js 'RENEWAL_ATTEMPT_DAYS = Object.freeze([0, 1, 3])' "retry schedule is exactly days 0/1/3"
assert_contains api/_billing.js "createCipheriv('aes-256-gcm'" "billing keys use AES-256-GCM"
assert_contains api/_billing.js 'generateCustomerKey' "customer keys are generated server-side"
assert_contains public/js/payment.js '/api/payment-config' "browser fetches public payment config"
assert_contains public/js/payment.js '/api/billing' "browser uses the billing API"
assert_contains public/js/payment.js 'requestBillingAuth' "browser starts Toss V2 billing auth"
assert_contains public/js/payment.js "billingRequest('prepare')" "browser prepares a recurring order"
assert_contains public/js/payment.js "billingRequest('activate'" "browser activates only through the billing API"
assert_contains public/js/payment.js 'cancelAtPeriodEnd' "cancellation is period-end only"
assert_contains public/js/payment.js '자동 환불되지 않습니다.' "recurring cancellation does not auto-refund"
assert_contains public/js/main.js 'history.replaceState' "billing credentials are removed from browser history"
assert_contains public/js/main.js 'activateBilling' "billing return invokes activation"
assert_absent public/js/payment.js "TossPayments('" "payment.js has no hardcoded Toss client key"
assert_absent public/stt-pay.html "TossPayments('" "stt-pay.html has no hardcoded Toss client key"
assert_absent public/js/payment.js "db.collection('subscriptions')" "browser does not read subscriptions directly"
assert_absent public/js/payment.js "db.collection('billingOrders')" "browser does not read billing orders directly"
assert_contains firestore.rules 'match /subscriptions/{uid}' "subscriptions client path is explicit"
assert_contains firestore.rules 'match /billingOrders/{orderId}' "billing orders client path is explicit"
assert_contains firestore.rules 'allow read, write: if false;' "billing records are client-denied"
assert_contains firestore.indexes.json '"fieldPath": "status", "order": "ASCENDING"' "bounded-work index starts with status"
assert_contains firestore.indexes.json '"fieldPath": "renewalReconciliationState", "order": "ASCENDING"' "bounded-work index includes reconciliation state"
assert_contains firestore.indexes.json '"fieldPath": "billingWorkDueAt", "order": "ASCENDING"' "bounded-work index ends with billingWorkDueAt"
assert_contains public/index.html '8,900' "homepage serves the recurring price"
assert_absent public/index.html '7,900' "homepage has no old recurring price"
